apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: readonly-tenant-b
  namespace: poc18-security-tenant-b

rules:
- apiGroups: ["", "apps"]

  resources:
    - pods
    - services
    - deployments

  verbs:
    - get
    - list
    - watch