tenant:
  name: poc14-reliability-tenant-b
  host: tenant-b.platform-demo.local

client:
  image: joseberrocal/poc09-client:ef84342
  replicas: 2

server:
  image: joseberrocal/poc09-server:ef84342
  replicas: 3

postgres:
  enabled: true
  createSecret: true

  image: postgres:16
  host: postgres-cluster-ip-service
  port: "5432"
  database: postgres
  user: postgres

  passwordSecretName: pgpassword
  passwordSecretKey: PGPASSWORD

  storageClassName: standard
  storageSize: 1Gi

resources:
  client: {}
  server: {}
  postgres:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

quota:
  requestsCpu: "2"
  requestsMemory: 2Gi
  limitsCpu: "4"
  limitsMemory: 4Gi
  pods: "10"
  persistentVolumeClaims: "2"