apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: {{ .Values.tenant.name }}
spec:
  replicas: {{ .Values.client.replicas | default 1 }}
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: {{ .Values.client.image }}
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL            
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: react-cache
              mountPath: /app/node_modules/.cache
          resources:
            requests:
              cpu: {{ .Values.resources.client.requests.cpu }}
              memory: {{ .Values.resources.client.requests.memory }}
            limits:
              cpu: {{ .Values.resources.client.limits.cpu }}
              memory: {{ .Values.resources.client.limits.memory }}
      volumes:
        - name: react-cache
          emptyDir: {}
      serviceAccountName: {{ .Values.serviceAccounts.client.name }}