{{- if .Values.postgres.externalCnpg }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-server-to-external-cnpg
  namespace: postgres-ha
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: postgres-ha
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.tenant.name }}
          podSelector:
            matchLabels:
              component: server
      ports:
        - protocol: TCP
          port: 5432
{{- end }}