{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
  namespace: {{ .Values.tenant.name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.storageClassName }}
  storageClassName: {{ .Values.postgres.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize | default "1Gi" }}
{{- end }}