{{- if .Values.postgres.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.passwordSecretName }}
  namespace: {{ .Values.tenant.name }}
type: Opaque
data:
  {{ .Values.postgres.passwordSecretKey }}: {{ .Values.postgres.password | b64enc }}
{{- end }}