apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
  namespace: {{ .Values.tenant.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize | default "1Gi" }}