apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: {{ .Values.tenant.name }}
spec:
  replicas: {{ .Values.server.replicas | default 1 }}
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: {{ .Values.server.image }}
          ports:
            - containerPort: 5000
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: PGUSER
              value: {{ .Values.postgres.user | default "postgres" | quote }}
            - name: PGHOST
              value: {{ .Values.postgres.host | default "postgres-cluster-ip-service" | quote }}
            - name: PGPORT
              value: {{ .Values.postgres.port | default "5432" | quote }}
            - name: PGDATABASE
              value: {{ .Values.postgres.database | default "postgres" | quote }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.passwordSecretName | quote }}
                  key: {{ .Values.postgres.passwordSecretKey | default "PGPASSWORD" | quote }}
      serviceAccountName: {{ .Values.serviceAccounts.server.name }}