apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.client.name }}
  namespace: {{ .Values.tenant.name }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.server.name }}
  namespace: {{ .Values.tenant.name }}

{{- if .Values.postgres.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.postgres.name }}
  namespace: {{ .Values.tenant.name }}
{{- end }}