apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc10-aks-tenant-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JoseBerrocal/platform-capstone.git
    targetRevision: main
    path: charts/tenant-platform
    helm:
      valueFiles:
        - ../../workloads/poc10-aks/tenant-a-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: poc10-aks-tenant-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true