apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod-test
  namespace: poc18-security-tenant-a
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: true
