apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-server-egress
  namespace: poc12-tenant-a
spec:
  podSelector:
    matchLabels:
      component: server
  policyTypes:
    - Egress
  egress: []
