apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: poc10-aks-tenant-a-default-deny
  namespace: poc10-aks-tenant-a
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
