apiVersion: v1
kind: ResourceQuota
metadata:
  name: poc10-aks-tenant-b-quota
  namespace: poc10-aks-tenant-b
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"
    persistentvolumeclaims: "2"
