tenant:
  name: poc11-aks-tenant-a
  host: tenant-a.platform-demo.local

client:
  image: joseberrocal/poc09-client:ef84342

server:
  image: joseberrocal/poc09-server:ef84342

postgres:
  image: postgres:16
  passwordSecretName: pgpassword
  storageClassName: managed-csi-platform
  storageSize: 1Gi

resources:
  client: {}
  server: {}
  postgres:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi