apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc09-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/JoseBerrocal/platform-capstone.git
    targetRevision: main
    path: workloads/poc09
  destination:
    server: https://kubernetes.default.svc
    namespace: poc09
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true