apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc10-aks-tenant-a-oci
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/joseberrocal/charts
      chart: tenant-platform
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/workloads/poc10-aks/tenant-a-values.yaml

    - repoURL: https://github.com/JoseBerrocal/platform-capstone.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: poc10-aks-tenant-a

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true