apiVersion: v1
kind: Namespace
metadata:
  name: postgres-ha
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ha
  namespace: postgres-ha
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  instances: 3

  storage:
    size: 1Gi