apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: joseberrocal/poc09-client:ba171a0
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
