apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-sa
  namespace: poc18-security-tenant-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-sa
  namespace: poc18-security-tenant-a